title: ergrelet's Blog
author:
  name: Erwan Grelet
  email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Technical blog, dealing with topics such as reverse engineering and software
  (de)obfuscation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ergrelet.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:day/:title:output_ext

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/ergrelet" }
    - { platform: twitter, user_url: "https://twitter.com/ergrelet" }
    - { platform: mastodon, user_url: "https://mastodon.social/@ergrelet" }

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-category-pages
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
